import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  FileText, Loader2, Copy, Download, CheckCircle,
  AlertTriangle, TrendingUp, Lightbulb, RefreshCw, Sparkles
} from 'lucide-react'
import { useReviewStore } from '../../store/reviewStore'
import axios from 'axios'
import toast from 'react-hot-toast'

const PRIORITY_STYLES = {
  CRITICAL: { color: '#DC2626', bg: '#FEF2F2', border: '#FECACA', dot: '#EF4444' },
  HIGH:     { color: '#D97706', bg: '#FFFBEB', border: '#FDE68A', dot: '#F59E0B' },
  MEDIUM:   { color: '#2563EB', bg: '#EFF6FF', border: '#BFDBFE', dot: '#3B82F6' },
}

const sectionVariants = {
  hidden:  { opacity: 0, y: 20 },
  visible: (i) => ({
    opacity: 1, y: 0,
    transition: { duration: 0.45, delay: i * 0.15, ease: 'easeOut' }
  }),
}

function SectionCard({ icon: Icon, title, children, color, bg, border, index }) {
  return (
    <motion.div
      custom={index}
      initial="hidden"
      animate="visible"
      variants={sectionVariants}
      className="rounded-2xl p-6 border"
      style={{ background: bg, borderColor: border }}
    >
      <div className="flex items-center gap-3 mb-4">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0"
          style={{ background: `${color}18`, border: `1.5px solid ${color}30` }}>
          <Icon size={16} style={{ color }} />
        </div>
        <h3 className="font-bold text-sm uppercase tracking-wider" style={{ color }}>
          {title}
        </h3>
      </div>
      {children}
    </motion.div>
  )
}

function EmptyState({ onGenerate, loading }) {
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.97 }}
      animate={{ opacity: 1, scale: 1 }}
      className="card-3d p-12 text-center"
    >
      <div className="w-20 h-20 rounded-2xl flex items-center justify-center mx-auto mb-6"
        style={{ background: '#FFF3E8', border: '2px solid #FED7AA' }}>
        <FileText size={34} style={{ color: '#FF7A00' }} />
      </div>
      <h3 className="font-bold text-xl mb-3" style={{ color: '#1E293B', fontFamily: 'DM Sans, sans-serif' }}>
        Generate Executive Brief
      </h3>
      <p className="text-sm leading-relaxed mb-8 max-w-md mx-auto" style={{ color: '#64748B' }}>
        Transform your review intelligence data into a concise C-suite ready brief with situation
        analysis, business impact assessment, and prioritised action items — generated by AI from your report data.
      </p>
      <div className="grid grid-cols-3 gap-3 max-w-sm mx-auto mb-8">
        {[
          { icon: TrendingUp,  label: 'Situation Analysis',  color: '#2563EB', bg: '#DBEAFE' },
          { icon: AlertTriangle, label: 'Business Impact',   color: '#D97706', bg: '#FEF3C7' },
          { icon: Lightbulb,   label: 'Action Items',        color: '#28C76F', bg: '#DCFCE7' },
        ].map(({ icon: Icon, label, color, bg }) => (
          <div key={label} className="rounded-xl p-3 text-center"
            style={{ background: bg, border: `1px solid ${color}30` }}>
            <Icon size={18} className="mx-auto mb-1.5" style={{ color }} />
            <div className="text-xs font-semibold leading-tight" style={{ color }}>{label}</div>
          </div>
        ))}
      </div>
      <button
        onClick={onGenerate}
        disabled={loading}
        className="inline-flex items-center gap-2 px-8 py-3.5 rounded-2xl font-bold text-white text-sm transition-all disabled:opacity-60"
        style={{
          background: '#FF7A00',
          boxShadow: '0 6px 24px rgba(255,122,0,0.35)',
        }}
      >
        {loading ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
        {loading ? 'Generating…' : 'Generate Brief'}
      </button>
    </motion.div>
  )
}

function ThinkingIndicator() {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="card-3d p-12 text-center"
    >
      <div className="relative w-16 h-16 mx-auto mb-6">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
          className="w-16 h-16 rounded-full absolute inset-0"
          style={{ border: '3px solid #F1F5F9', borderTop: '3px solid #FF7A00' }}
        />
        <div className="absolute inset-0 flex items-center justify-center">
          <FileText size={20} style={{ color: '#FF7A00' }} />
        </div>
      </div>
      <div className="font-bold text-lg mb-2" style={{ color: '#1E293B' }}>
        Drafting Executive Brief…
      </div>
      <div className="flex items-center justify-center gap-1.5 mb-4">
        {['Analysing data', 'Structuring insights', 'Drafting actions'].map((step, i) => (
          <motion.span
            key={step}
            animate={{ opacity: [0.4, 1, 0.4] }}
            transition={{ duration: 1.6, repeat: Infinity, delay: i * 0.5 }}
            className="text-xs font-medium px-2 py-1 rounded-lg"
            style={{ background: '#FFF3E8', color: '#FF7A00' }}
          >
            {step}
          </motion.span>
        ))}
      </div>
      <p className="text-sm" style={{ color: '#94A3B8' }}>
        The LLM is synthesising your review data into a boardroom-ready brief…
      </p>
    </motion.div>
  )
}

export default function ExecutiveBriefTab() {
  const { report } = useReviewStore()
  const [brief, setBrief] = useState(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  if (!report) return null

  const handleGenerate = async () => {
    setLoading(true)
    try {
      const { data } = await axios.post('/api/brief', { report })
      setBrief(data)
    } catch (e) {
      toast.error('Failed to generate brief. Ensure the backend and Ollama are running.')
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = async () => {
    if (!brief) return
    const text = [
      `EXECUTIVE BRIEF — ${brief.summary_headline || brief.product_name}`,
      '',
      'SITUATION',
      brief.situation,
      '',
      'BUSINESS IMPACT',
      brief.business_impact,
      '',
      'RECOMMENDED ACTIONS',
      ...(brief.recommended_actions || []).map(
        (a, i) => `${i + 1}. [${a.priority}] ${a.action}`
      ),
      '',
      `Confidence Score: ${brief.confidence_score}/100`,
      `Generated: ${new Date(brief.generated_at).toLocaleString()}`,
      'Generated by ReviewIQ Agentic AI',
    ].join('\n')
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      toast.success('Brief copied to clipboard!')
      setTimeout(() => setCopied(false), 2500)
    } catch {
      toast.error('Could not copy to clipboard')
    }
  }

  const handleDownloadPDF = () => {
    if (!brief) return
    const params = new URLSearchParams({
      situation:        brief.situation || '',
      business_impact:  brief.business_impact || '',
      headline:         brief.summary_headline || '',
      product_name:     brief.product_name || '',
      confidence_score: String(brief.confidence_score || 75),
    })
    window.open(`/api/brief/download/pdf?${params.toString()}`, '_blank')
  }

  const handleDownloadDocx = () => {
    if (!brief) return
    // Build a simple text-based docx via a blob download
    const content = [
      `EXECUTIVE BRIEF`,
      `${brief.summary_headline || brief.product_name}`,
      '',
      'SITUATION',
      brief.situation,
      '',
      'BUSINESS IMPACT',
      brief.business_impact,
      '',
      'RECOMMENDED ACTIONS',
      ...(brief.recommended_actions || []).map(
        (a, i) => `${i + 1}. [${a.priority}] ${a.action}`
      ),
      '',
      `Confidence Score: ${brief.confidence_score}/100`,
      `Generated: ${new Date(brief.generated_at).toLocaleString()}`,
      'Generated by ReviewIQ Agentic AI',
    ].join('\r\n')

    const blob = new Blob([content], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
    const url  = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `executive_brief_${Date.now()}.docx`
    document.body.appendChild(link)
    link.click()
    link.remove()
    URL.revokeObjectURL(url)
    toast.success('Brief downloaded as .docx')
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="font-bold text-2xl" style={{ color: '#1E293B', fontFamily: 'DM Sans, sans-serif' }}>
            Executive Brief
          </h2>
          <p className="text-sm mt-1" style={{ color: '#64748B' }}>
            AI-generated C-suite summary from your review intelligence report
          </p>
        </div>
        {brief && (
          <motion.button
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white transition-all disabled:opacity-60"
            style={{ background: '#FF7A00', boxShadow: '0 4px 16px rgba(255,122,0,0.3)' }}
          >
            {loading
              ? <><Loader2 size={14} className="animate-spin" /> Regenerating…</>
              : <><RefreshCw size={14} /> Regenerate</>
            }
          </motion.button>
        )}
      </div>

      {/* Content */}
      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
            <ThinkingIndicator />
          </motion.div>
        ) : !brief ? (
          <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
            <EmptyState onGenerate={handleGenerate} loading={loading} />
          </motion.div>
        ) : (
          <motion.div
            key="brief"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="space-y-4"
          >
            {/* Headline card */}
            <motion.div
              custom={0}
              initial="hidden"
              animate="visible"
              variants={sectionVariants}
              className="rounded-2xl p-6"
              style={{ background: '#1E293B', border: '1px solid #334155' }}
            >
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                  style={{ background: '#FF7A0020', border: '1.5px solid #FF7A0040' }}>
                  <Sparkles size={18} style={{ color: '#FF7A00' }} />
                </div>
                <div>
                  <div className="text-xs font-bold uppercase tracking-wider mb-1.5"
                    style={{ color: '#FF7A00' }}>
                    Executive Summary
                  </div>
                  <p className="font-bold text-lg leading-snug"
                    style={{ color: '#F8FAFC', fontFamily: 'DM Sans, sans-serif' }}>
                    {brief.summary_headline || `Review Intelligence Report — ${brief.product_name}`}
                  </p>
                </div>
              </div>
            </motion.div>

            {/* Situation */}
            <SectionCard
              index={1}
              icon={TrendingUp}
              title="Situation"
              color="#2563EB"
              bg="#EFF6FF"
              border="#BFDBFE"
            >
              <p className="text-sm leading-relaxed" style={{ color: '#1E40AF' }}>
                {brief.situation}
              </p>
            </SectionCard>

            {/* Business Impact */}
            <SectionCard
              index={2}
              icon={AlertTriangle}
              title="Business Impact"
              color="#D97706"
              bg="#FFFBEB"
              border="#FDE68A"
            >
              <p className="text-sm leading-relaxed" style={{ color: '#92400E' }}>
                {brief.business_impact}
              </p>
            </SectionCard>

            {/* Recommended Actions */}
            <SectionCard
              index={3}
              icon={Lightbulb}
              title="Recommended Actions"
              color="#16A34A"
              bg="#F0FDF4"
              border="#BBF7D0"
            >
              <div className="space-y-3">
                {(brief.recommended_actions || []).map((action, i) => {
                  const pStyle = PRIORITY_STYLES[action.priority] || PRIORITY_STYLES.MEDIUM
                  return (
                    <motion.div
                      key={i}
                      custom={i}
                      initial="hidden"
                      animate="visible"
                      variants={sectionVariants}
                      className="flex items-start gap-3 p-3.5 rounded-xl border"
                      style={{ background: '#FFFFFF', borderColor: '#E5E7EB' }}
                    >
                      <div className="flex-shrink-0 mt-0.5">
                        <span className="text-xs font-bold px-2 py-0.5 rounded-lg"
                          style={{ background: pStyle.bg, color: pStyle.color, border: `1px solid ${pStyle.border}` }}>
                          {action.priority}
                        </span>
                      </div>
                      <div className="flex items-start gap-2 flex-1">
                        <span className="text-sm font-bold flex-shrink-0"
                          style={{ color: '#94A3B8', minWidth: '1.2rem' }}>
                          {i + 1}.
                        </span>
                        <p className="text-sm" style={{ color: '#1E293B' }}>{action.action}</p>
                      </div>
                    </motion.div>
                  )
                })}
              </div>
            </SectionCard>

            {/* Footer: confidence + actions */}
            <motion.div
              custom={4}
              initial="hidden"
              animate="visible"
              variants={sectionVariants}
              className="flex items-center justify-between flex-wrap gap-4 rounded-2xl p-5 border"
              style={{ background: '#FFFFFF', borderColor: '#E5E7EB' }}
            >
              <div className="flex items-center gap-4">
                <div className="flex items-center gap-2">
                  <CheckCircle size={16} style={{ color: '#28C76F' }} />
                  <span className="text-sm font-semibold" style={{ color: '#1E293B' }}>
                    Confidence Score
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full text-sm font-bold"
                    style={{
                      background: brief.confidence_score >= 75 ? '#DCFCE7' : brief.confidence_score >= 50 ? '#FEF3C7' : '#FEE2E2',
                      color:      brief.confidence_score >= 75 ? '#16A34A' : brief.confidence_score >= 50 ? '#D97706'  : '#DC2626',
                    }}>
                    {brief.confidence_score}/100
                  </span>
                </div>
                <span className="text-xs" style={{ color: '#94A3B8' }}>
                  {brief.generated_at
                    ? new Date(brief.generated_at).toLocaleString()
                    : 'Just now'}
                </span>
              </div>

              {/* Action buttons */}
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all"
                  style={{
                    background: copied ? '#DCFCE7' : '#FFFFFF',
                    borderColor: copied ? '#86EFAC' : '#E5E7EB',
                    color: copied ? '#16A34A' : '#475569',
                  }}
                >
                  {copied ? <CheckCircle size={13} /> : <Copy size={13} />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={handleDownloadPDF}
                  className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all"
                  style={{
                    background: '#FFFFFF',
                    borderColor: '#E5E7EB',
                    color: '#475569',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.borderColor = '#FF7A00'; e.currentTarget.style.color = '#FF7A00' }}
                  onMouseLeave={e => { e.currentTarget.style.borderColor = '#E5E7EB'; e.currentTarget.style.color = '#475569' }}
                >
                  <Download size={13} />
                  PDF
                </button>
                <button
                  onClick={handleDownloadDocx}
                  className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold border transition-all"
                  style={{
                    background: '#FFFFFF',
                    borderColor: '#E5E7EB',
                    color: '#475569',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.borderColor = '#2563EB'; e.currentTarget.style.color = '#2563EB' }}
                  onMouseLeave={e => { e.currentTarget.style.borderColor = '#E5E7EB'; e.currentTarget.style.color = '#475569' }}
                >
                  <Download size={13} />
                  .docx
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
